# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(spout_bone) {transformation: [-1.2083f,0f,0f,0f,0f,1.2083f,0f,0f,0f,0f,-1.2083f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 0}
$data merge entity $(spout_controller_bone) {transformation: [-1f,0f,0f,0.2188f,0f,1f,0f,0.9375f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 0}
$data merge entity $(drink_bone4) {transformation: [0f,0f,0f,0.5013f,0f,0f,0f,1.0566f,0f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 0}
$data merge entity $(glass_bone4) {transformation: [-1f,0f,0f,0.5f,0f,1f,0f,1.1881f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 0}