# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute if entity @s[tag=animation.sculkadillo.animation.grab.playing] run function fossil_frights:animations/dinocoin/crane/rig/animations/grab/zzz/on_tick
execute if entity @s[tag=animation.sculkadillo.animation.pull.playing] run function fossil_frights:animations/dinocoin/crane/rig/animations/pull/zzz/on_tick
execute if entity @s[tag=animation.sculkadillo.animation.pull_back.playing] run function fossil_frights:animations/dinocoin/crane/rig/animations/pull_back/zzz/on_tick
execute if entity @s[tag=animation.sculkadillo.animation.idle_right.playing] run function fossil_frights:animations/dinocoin/crane/rig/animations/idle_right/zzz/on_tick
execute if entity @s[tag=animation.sculkadillo.animation.idle_left.playing] run function fossil_frights:animations/dinocoin/crane/rig/animations/idle_left/zzz/on_tick
execute on passengers run rotate @s ~ ~