# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
# Data Manager: Prepare for Read / Write
execute store result storage fossil_frights:vending_machine_aj_temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Read
function fossil_frights:animations/dinocoin/vending_machine/runtime/data_manager/read with storage fossil_frights:vending_machine_aj_temp args
execute unless data storage fossil_frights:vending_machine_aj_temp {entry:{data:{rig_hash: 'b8b7a3e491ce6a2992066e1945387c2a2c67d9f63a50cf45fd28d6d9838a8bda'}}} run function fossil_frights:animations/dinocoin/vending_machine/runtime/remove/outdated_rig
function fossil_frights:animations/tasks/easy/tnt_test/detonator/rig/remove/this/zzz/0 with storage fossil_frights:vending_machine_aj_temp entry.data.uuids_by_name
function fossil_frights:animations/dinocoin/vending_machine/runtime/remove/entity_stack