# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute if entity @s[tag=animation.vending_machine.animation.fill_bubblybat.playing] run function fossil_frights:animations/dinocoin/vending_machine/rig/animations/fill_bubblybat/zzz/on_tick
execute if entity @s[tag=animation.vending_machine.animation.fill_pteranadontwist.playing] run function fossil_frights:animations/dinocoin/vending_machine/rig/animations/fill_pteranadontwist/zzz/on_tick
execute if entity @s[tag=animation.vending_machine.animation.fill_fossilfizz.playing] run function fossil_frights:animations/dinocoin/vending_machine/rig/animations/fill_fossilfizz/zzz/on_tick
execute if entity @s[tag=animation.vending_machine.animation.fill_choruscola.playing] run function fossil_frights:animations/dinocoin/vending_machine/rig/animations/fill_choruscola/zzz/on_tick
execute if entity @s[tag=animation.vending_machine.animation.fill_raptorrush.playing] run function fossil_frights:animations/dinocoin/vending_machine/rig/animations/fill_raptorrush/zzz/on_tick
execute if entity @s[tag=animation.vending_machine.animation.fill_velocitea.playing] run function fossil_frights:animations/dinocoin/vending_machine/rig/animations/fill_velocitea/zzz/on_tick
execute on passengers run rotate @s ~ ~