# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
tp @s ~ ~ ~ ~ ~
# Data Manager: Prepare for Read / Write
execute store result storage fossil_frights:vending_machine_aj_temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Read
function fossil_frights:animations/dinocoin/vending_machine/runtime/data_manager/read with storage fossil_frights:vending_machine_aj_temp args
execute at @s on passengers run rotate @s ~ ~