# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage fossil_frights:animations/tasks/easy/tnt_test/detonator/rig rig_hash set value 'b8b7a3e491ce6a2992066e1945387c2a2c67d9f63a50cf45fd28d6d9838a8bda'
scoreboard objectives add aj.activate.frame dummy