# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
# Data Manager: Prepare for Read / Write
execute store result storage fossil_frights:vending_machine_aj_temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Read
function fossil_frights:animations/dinocoin/vending_machine/runtime/data_manager/read with storage fossil_frights:vending_machine_aj_temp args
execute unless data storage fossil_frights:vending_machine_aj_temp {entry:{data:{rig_hash: 'a83918f006c7f640d609c973b328cfd09370653fda2f656396bf18ca88aac3ba'}}} run function fossil_frights:animations/dinocoin/vending_machine/runtime/remove/outdated_rig
function fossil_frights:animations/tasks/medium/feed_the_plants/flytrap/rig/remove/this/zzz/0 with storage fossil_frights:vending_machine_aj_temp entry.data.uuids_by_name
function fossil_frights:animations/dinocoin/vending_machine/runtime/remove/entity_stack