# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data remove storage fossil_frights:vending_machine_aj_temp entry
$data modify storage fossil_frights:vending_machine_aj_temp entry set from storage fossil_frights:vending_machine_aj_data "$(id)"