# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
# Data Manager: Prepare for Read / Write
execute store result storage fossil_frights:vending_machine_aj_temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Read
function fossil_frights:animations/dinocoin/vending_machine/runtime/data_manager/read with storage fossil_frights:vending_machine_aj_temp args
data remove storage fossil_frights:vending_machine_aj_temp args
$execute store result storage fossil_frights:vending_machine_aj_temp args.frame int 1 run scoreboard players set @s aj.idle.frame $(frame)
execute at @s run function fossil_frights:animations/dinocoin/sarcophagus/rig/animations/idle/zzz/set_frame with storage fossil_frights:vending_machine_aj_temp args