# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(shell_bone) {transformation: [-1f,0f,0f,-0.5f,0f,1f,0f,0.3462f,0f,0f,-1f,-0.4299f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_ear_cube) {transformation: [-1f,0f,0f,-0.4062f,0f,1f,0f,0.6875f,0f,0f,-1f,-0.15f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_ear_cube) {transformation: [-1f,0f,0f,-0.5937f,0f,1f,0f,0.6875f,0f,0f,-1f,-0.15f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head_bone) {transformation: [-1f,0f,0f,-0.5f,0f,1f,0f,0.6563f,0f,0f,-1f,-0.25f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(tail) {transformation: [-1f,0f,0f,-0.5f,0f,1f,0f,0.375f,0f,0f,-1f,-0.8125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_koin_bone) {transformation: [0f,0f,0f,-0.3292f,0f,0f,0f,0.4143f,0f,0f,0f,-0.1885f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(front_left_leg_bone) {transformation: [-1f,0f,0f,-0.375f,0f,1f,0f,0.5156f,0f,0f,-1f,-0.4219f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(front_right_leg_bone) {transformation: [-1f,0f,0f,-0.625f,0f,0.9397f,-0.342f,0.4844f,0f,-0.342f,-0.9397f,-0.3906f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(back_left_leg_bone) {transformation: [-1f,0f,0f,-0.375f,0f,1f,0f,0.1875f,0f,0f,-1f,-0.75f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(back_right_leg_bone) {transformation: [-1f,0f,0f,-0.625f,0f,1f,0f,0.1875f,0f,0f,-1f,-0.75f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(handle_bone) {transformation: [-1f,0f,0f,-0.5f,0f,1f,0f,0.0625f,0f,0f,-1f,-0.0625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(lever) {transformation: [-1f,0f,0f,-0.5f,0f,1f,0f,0.0625f,0f,0f,-1f,-0.0625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}