# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(turntable_bone) {transformation: [0f,0f,-1f,0.5f,0f,1f,0f,0.9688f,1f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 0}
$data merge entity $(drink_bone5) {transformation: [0f,0f,-1f,0.5f,0f,0.5556f,0f,1.1608f,1f,0f,0f,-0.0013f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 0}
$data merge entity $(glass_bone5) {transformation: [0f,0f,-1f,0.5f,0f,1f,0f,1.1881f,1f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 0}