# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage fossil_frights:animations/dinocoin/crane/rig rig_hash set value '88c0ff59deebe3cd388ab884f292ed13c4c73d68d1a53a287dc24a86f92bfb78'
scoreboard objectives add aj.grab.frame dummy
scoreboard objectives add aj.pull.frame dummy
scoreboard objectives add aj.pull_back.frame dummy
scoreboard objectives add aj.idle_right.frame dummy
scoreboard objectives add aj.idle_left.frame dummy