# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage fossil_frights:vending_machine_aj_temp args.current_uuid set from storage fossil_frights:vending_machine_aj_temp uuids[-1].uuid
data remove storage fossil_frights:vending_machine_aj_temp uuids[-1]
function fossil_frights:animations/dinocoin/vending_machine/runtime/remove/entity_stack_by_uuid with storage fossil_frights:vending_machine_aj_temp args
scoreboard players remove #aj.length aj.i 1
execute if score #aj.length aj.i matches 1.. run function fossil_frights:animations/dinocoin/vending_machine/runtime/remove/loop_over_uuids