# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(shell_bone) {transformation: [-1f,0f,0.0097f,-0.5f,0f,1f,0f,0.3462f,-0.0097f,0f,-1f,-0.4299f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_ear_cube) {transformation: [-0.9998f,0.0179f,0f,-0.4062f,0.0179f,0.9998f,0f,0.6875f,0f,0f,-1f,-0.15f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_ear_cube) {transformation: [-1f,0f,0f,-0.5937f,0f,1f,0f,0.6875f,0f,0f,-1f,-0.15f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head_bone) {transformation: [-1f,0f,0f,-0.5f,0f,1f,0f,0.6563f,0f,0f,-1f,-0.25f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(tail) {transformation: [-1f,0f,0f,-0.5f,0f,1f,0f,0.375f,0f,0f,-1f,-0.8125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_koin_bone) {transformation: [0f,0f,0f,-0.3716f,0f,0f,0f,0.3583f,0f,0f,0f,-0.33f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(front_left_leg_bone) {transformation: [-0.9998f,-0.0136f,-0.0138f,-0.375f,-0.0138f,0.9998f,0.0118f,0.5156f,0.0137f,0.012f,-0.9998f,-0.4219f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(front_right_leg_bone) {transformation: [-0.9998f,-0.0067f,-0.0183f,-0.625f,0f,0.9397f,-0.342f,0.4844f,0.0195f,-0.342f,-0.9395f,-0.3938f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}