# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
scoreboard players remove @s aj.tween_duration 1
execute if score @s aj.tween_duration matches 1.. run return 1
execute if score @s aj.tween_duration matches 0 on passengers run data modify entity @s interpolation_duration set value 0
data remove storage fossil_frights:vending_machine_aj_temp args
execute store result storage fossil_frights:vending_machine_aj_temp args.frame int 1 run scoreboard players get @s aj.fill_raptorrush.frame
function fossil_frights:animations/dinocoin/vending_machine/rig/animations/fill_raptorrush/zzz/apply_frame with storage fossil_frights:vending_machine_aj_temp args
execute if score @s aj.fill_raptorrush.frame matches 30 run return run function fossil_frights:animations/dinocoin/vending_machine/rig/animations/fill_raptorrush/zzz/loop_mode_stop
scoreboard players add @s aj.fill_raptorrush.frame 1