# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
scoreboard players set @s aj.fill_fossilfizz.frame 30
tag @s add aj.transforms_only
execute at @s run function fossil_frights:animations/dinocoin/vending_machine/rig/animations/fill_fossilfizz/zzz/set_frame {frame: 30}
tag @s remove aj.transforms_only
tag @s remove animation.vending_machine.animation.fill_fossilfizz.playing
