# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$function fossil_frights:animations/dinocoin/vending_machine/rig/animations/fill_bubblybat/zzz/frames/$(frame) with storage fossil_frights:vending_machine_aj_temp entry.data.uuids_by_name
execute on passengers run data modify entity @s start_interpolation set value -1
return 1