# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
# Data Manager: Prepare for Read / Write
execute store result storage fossil_frights:vending_machine_aj_temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Read
function fossil_frights:animations/dinocoin/vending_machine/runtime/data_manager/read with storage fossil_frights:vending_machine_aj_temp args
function fossil_frights:animations/dinocoin/crane/rig/animations/pause_all
tag @s add animation.sculkadillo.animation.grab.playing
$scoreboard players set @s aj.tween_duration $(duration)
$scoreboard players set @s aj.grab.frame $(to_frame)
scoreboard players operation #this aj.i = @s aj.tween_duration
tag @s add aj.transforms_only
execute at @s run function fossil_frights:animations/dinocoin/crane/rig/animations/grab/zzz/apply_frame {frame: 0}
$execute at @s run function fossil_frights:animations/dinocoin/crane/rig/animations/grab/zzz/apply_frame {frame: $(to_frame)}
tag @s remove aj.transforms_only
execute on passengers store result entity @s interpolation_duration int 1 run scoreboard players get #this aj.i