# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data remove storage fossil_frights:vending_machine_aj_temp uuids
execute on passengers run function fossil_frights:animations/dinocoin/vending_machine/runtime/util/zzz/0