# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
# Data Manager: Prepare for Read / Write
execute store result storage fossil_frights:vending_machine_aj_temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Read
function fossil_frights:animations/dinocoin/vending_machine/runtime/data_manager/read with storage fossil_frights:vending_machine_aj_temp args
execute if score @s aj.idle_left.frame matches 17.. run scoreboard players set @s aj.idle_left.frame 1
data remove storage fossil_frights:vending_machine_aj_temp args
execute store result storage fossil_frights:vending_machine_aj_temp args.frame int 1 run scoreboard players get @s aj.idle_left.frame
execute at @s run function fossil_frights:animations/dinocoin/crane/rig/animations/idle_left/zzz/apply_frame with storage fossil_frights:vending_machine_aj_temp args
scoreboard players add @s aj.idle_left.frame 1