# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(trapdoor_ne_bone) {transformation: [-1f,0f,0f,-0.0937f,0f,1f,0f,0f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 0}
$data merge entity $(trapdoor_se_bone) {transformation: [-1f,0f,0f,0f,0f,1f,0f,0f,0f,0f,-1f,-0.0937f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 0}
$data merge entity $(trapdoor_sw_bone) {transformation: [-1f,0f,0f,0.0938f,0f,1f,0f,0f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 0}
$data merge entity $(trapdoor_nw_bone) {transformation: [-1f,0f,0f,0f,0f,1f,0f,0f,0f,0f,-1f,0.0938f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 0}
$data merge entity $(spout_bone) {transformation: [-1.2083f,0f,0f,-0.0937f,0f,1.2083f,0f,0f,0f,0f,-1.2083f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 0}
$data merge entity $(spout_controller_bone) {transformation: [-1f,0f,0f,0.125f,0f,1f,0f,0.9375f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 0}
$data merge entity $(turntable_bone) {transformation: [-1f,0f,0f,0.5f,0f,1f,0f,0.4271f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 0}
$data merge entity $(mainplate_bone) {transformation: [-1f,0f,0f,0f,0f,1f,0f,0.2708f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 0}