# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(strawtrapdoor_bone) {transformation: [-1f,0f,0f,0.5f,0f,1f,0f,2f,0f,0f,-1f,-0.0625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 0}
$data merge entity $(holder_l_bone) {transformation: [-1f,0f,0f,0.375f,0f,1f,0f,1f,0f,0f,-1f,0.1844f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 0}
$data merge entity $(holder_r_bone) {transformation: [-1f,0f,0f,0.375f,0f,1f,0f,1f,0f,0f,-1f,0.1906f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 0}
$data merge entity $(straw_bone3) {transformation: [-1f,0f,0f,0.1875f,0f,0.9962f,-0.0872f,0.9751f,0f,-0.0872f,-0.9962f,0.1602f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 0}