# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data modify storage fossil_frights:vending_machine_aj_temp args.uuid set from storage fossil_frights:vending_machine_aj_data "$(id)".uuid
scoreboard players set #success aj.i 0
function fossil_frights:animations/dinocoin/vending_machine/runtime/data_manager/zzz/1 with storage fossil_frights:vending_machine_aj_temp args