# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute store result score @s aj.id run scoreboard players add aj.last_id aj.id 1
# Data Manager: Initalize per-entity storage
function fossil_frights:animations/dinocoin/vending_machine/runtime/gu/get_entity_uuid_string
data modify storage fossil_frights:vending_machine_aj_temp args.uuid set from storage fossil_frights:vending_machine_aj_gu out
execute store result storage fossil_frights:vending_machine_aj_temp args.id int 1 run scoreboard players get @s aj.id
function fossil_frights:animations/dinocoin/vending_machine/runtime/data_manager/create_entry with storage fossil_frights:vending_machine_aj_temp args
# Data Manager: Prepare for Read / Write
execute store result storage fossil_frights:vending_machine_aj_temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Read
function fossil_frights:animations/dinocoin/vending_machine/runtime/data_manager/read with storage fossil_frights:vending_machine_aj_temp args
data modify storage fossil_frights:vending_machine_aj_temp entry.data.uuids append from storage fossil_frights:vending_machine_aj_gu out
data modify storage fossil_frights:vending_machine_aj_temp entry.data.root_uuid set from storage fossil_frights:vending_machine_aj_gu out
data modify storage fossil_frights:vending_machine_aj_temp entry.data.blueprint_id set value "fossil_frights:animations/dinocoin/crane/rig"
data modify storage fossil_frights:vending_machine_aj_temp entry.data.rig_hash set value "88c0ff59deebe3cd388ab884f292ed13c4c73d68d1a53a287dc24a86f92bfb78"
tp @s ~ ~ ~ ~ ~
execute on passengers if entity @s[tag=animation.sculkadillo.node.shell_bone] run function fossil_frights:animations/dinocoin/crane/rig/zzz/summon/as_node/shell_bone
data modify storage fossil_frights:vending_machine_aj_temp entry.data.uuids append from storage fossil_frights:vending_machine_aj_gu out
data modify storage fossil_frights:vending_machine_aj_temp entry.data.uuids_by_name.shell_bone set from storage fossil_frights:vending_machine_aj_gu out
execute on passengers if entity @s[tag=animation.sculkadillo.node.left_ear_cube] run function fossil_frights:animations/dinocoin/crane/rig/zzz/summon/as_node/left_ear_cube
data modify storage fossil_frights:vending_machine_aj_temp entry.data.uuids append from storage fossil_frights:vending_machine_aj_gu out
data modify storage fossil_frights:vending_machine_aj_temp entry.data.uuids_by_name.left_ear_cube set from storage fossil_frights:vending_machine_aj_gu out
execute on passengers if entity @s[tag=animation.sculkadillo.node.right_ear_cube] run function fossil_frights:animations/dinocoin/crane/rig/zzz/summon/as_node/right_ear_cube
data modify storage fossil_frights:vending_machine_aj_temp entry.data.uuids append from storage fossil_frights:vending_machine_aj_gu out
data modify storage fossil_frights:vending_machine_aj_temp entry.data.uuids_by_name.right_ear_cube set from storage fossil_frights:vending_machine_aj_gu out
execute on passengers if entity @s[tag=animation.sculkadillo.node.head_bone] run function fossil_frights:animations/dinocoin/crane/rig/zzz/summon/as_node/head_bone
data modify storage fossil_frights:vending_machine_aj_temp entry.data.uuids append from storage fossil_frights:vending_machine_aj_gu out
data modify storage fossil_frights:vending_machine_aj_temp entry.data.uuids_by_name.head_bone set from storage fossil_frights:vending_machine_aj_gu out
execute on passengers if entity @s[tag=animation.sculkadillo.node.tail] run function fossil_frights:animations/dinocoin/crane/rig/zzz/summon/as_node/tail
data modify storage fossil_frights:vending_machine_aj_temp entry.data.uuids append from storage fossil_frights:vending_machine_aj_gu out
data modify storage fossil_frights:vending_machine_aj_temp entry.data.uuids_by_name.tail set from storage fossil_frights:vending_machine_aj_gu out
execute on passengers if entity @s[tag=animation.sculkadillo.node.arm_koin_bone] run function fossil_frights:animations/dinocoin/crane/rig/zzz/summon/as_node/arm_koin_bone
data modify storage fossil_frights:vending_machine_aj_temp entry.data.uuids append from storage fossil_frights:vending_machine_aj_gu out
data modify storage fossil_frights:vending_machine_aj_temp entry.data.uuids_by_name.arm_koin_bone set from storage fossil_frights:vending_machine_aj_gu out
execute on passengers if entity @s[tag=animation.sculkadillo.node.front_left_leg_bone] run function fossil_frights:animations/dinocoin/crane/rig/zzz/summon/as_node/front_left_leg_bone
data modify storage fossil_frights:vending_machine_aj_temp entry.data.uuids append from storage fossil_frights:vending_machine_aj_gu out
data modify storage fossil_frights:vending_machine_aj_temp entry.data.uuids_by_name.front_left_leg_bone set from storage fossil_frights:vending_machine_aj_gu out
execute on passengers if entity @s[tag=animation.sculkadillo.node.front_right_leg_bone] run function fossil_frights:animations/dinocoin/crane/rig/zzz/summon/as_node/front_right_leg_bone
data modify storage fossil_frights:vending_machine_aj_temp entry.data.uuids append from storage fossil_frights:vending_machine_aj_gu out
data modify storage fossil_frights:vending_machine_aj_temp entry.data.uuids_by_name.front_right_leg_bone set from storage fossil_frights:vending_machine_aj_gu out
execute on passengers if entity @s[tag=animation.sculkadillo.node.back_left_leg_bone] run function fossil_frights:animations/dinocoin/crane/rig/zzz/summon/as_node/back_left_leg_bone
data modify storage fossil_frights:vending_machine_aj_temp entry.data.uuids append from storage fossil_frights:vending_machine_aj_gu out
data modify storage fossil_frights:vending_machine_aj_temp entry.data.uuids_by_name.back_left_leg_bone set from storage fossil_frights:vending_machine_aj_gu out
execute on passengers if entity @s[tag=animation.sculkadillo.node.back_right_leg_bone] run function fossil_frights:animations/dinocoin/crane/rig/zzz/summon/as_node/back_right_leg_bone
data modify storage fossil_frights:vending_machine_aj_temp entry.data.uuids append from storage fossil_frights:vending_machine_aj_gu out
data modify storage fossil_frights:vending_machine_aj_temp entry.data.uuids_by_name.back_right_leg_bone set from storage fossil_frights:vending_machine_aj_gu out
execute on passengers if entity @s[tag=animation.sculkadillo.node.handle_bone] run function fossil_frights:animations/dinocoin/crane/rig/zzz/summon/as_node/handle_bone
data modify storage fossil_frights:vending_machine_aj_temp entry.data.uuids append from storage fossil_frights:vending_machine_aj_gu out
data modify storage fossil_frights:vending_machine_aj_temp entry.data.uuids_by_name.handle_bone set from storage fossil_frights:vending_machine_aj_gu out
execute on passengers if entity @s[tag=animation.sculkadillo.node.lever] run function fossil_frights:animations/dinocoin/crane/rig/zzz/summon/as_node/lever
data modify storage fossil_frights:vending_machine_aj_temp entry.data.uuids append from storage fossil_frights:vending_machine_aj_gu out
data modify storage fossil_frights:vending_machine_aj_temp entry.data.uuids_by_name.lever set from storage fossil_frights:vending_machine_aj_gu out
# Data Manager: Write
function fossil_frights:animations/dinocoin/vending_machine/runtime/data_manager/write with storage fossil_frights:vending_machine_aj_temp args
function fossil_frights:animations/dinocoin/crane/rig/zzz/set_default_pose
execute if data storage fossil_frights:vending_machine_aj_temp args.variant run function fossil_frights:animations/dinocoin/crane/rig/zzz/summon/zzz/variant_arg/no_variants_warning
execute if score #success aj.i matches 0 run return fail
execute if data storage fossil_frights:vending_machine_aj_temp args.animation run function fossil_frights:animations/dinocoin/crane/rig/zzz/summon/animation_arg/process with storage fossil_frights:vending_machine_aj_temp args
execute if score #success aj.i matches 0 run return fail
execute on passengers run rotate @s ~ ~
data modify entity @s teleport_duration set value 1
execute on passengers run data modify entity @s teleport_duration set value 1
tag @s remove aj.new
execute on passengers run tag @s remove aj.new