# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
# Data Manager: Prepare for Read / Write
execute store result storage fossil_frights:vending_machine_aj_temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Read
function fossil_frights:animations/dinocoin/vending_machine/runtime/data_manager/read with storage fossil_frights:vending_machine_aj_temp args
data remove storage fossil_frights:vending_machine_aj_temp args
data remove storage fossil_frights:vending_machine_aj_temp uuids
data modify storage fossil_frights:vending_machine_aj_temp uuids set from entity @s data.uuids
execute store result score #aj.length aj.i run data get storage fossil_frights:vending_machine_aj_temp uuids
execute if score #aj.length aj.i matches 1.. run function fossil_frights:animations/dinocoin/vending_machine/runtime/remove/loop_over_uuids
function fossil_frights:animations/dinocoin/vending_machine/runtime/remove/entity_stack