# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute if entity @s[tag=animation.talking_skull.animation.jump.playing] run function fossil_frights:animations/dinocoin/sarcophagus/rig/animations/jump/zzz/on_tick
execute if entity @s[tag=animation.talking_skull.animation.idle.playing] run function fossil_frights:animations/dinocoin/sarcophagus/rig/animations/idle/zzz/on_tick
execute on passengers run rotate @s ~ ~