# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(strawtrapdoor_bone) {transformation: [-1f,0f,0f,0.5f,0f,1f,0f,2f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 0}
$data merge entity $(holder_l_bone) {transformation: [-1f,0f,0f,0.375f,0f,1f,0f,1f,0f,0f,-1f,0.1875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 0}
$data merge entity $(holder_r_bone) {transformation: [-1f,0f,0f,0.375f,0f,1f,0f,1f,0f,0f,-1f,0.1875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 0}
$data merge entity $(spout_bone) {transformation: [-1.2083f,0f,0f,-0.0833f,0f,1.2083f,0f,0f,0f,0f,-1.2083f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 0}
$data merge entity $(spout_controller_bone) {transformation: [-1f,0f,0f,0.1354f,0f,1f,0f,0.9375f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 0}
$data merge entity $(straw_bone) {transformation: [-1f,0f,0f,0.1875f,0f,1f,0f,1.7861f,0f,0f,-1f,0.125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 0}