# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$execute as $(stick_bone) run function fossil_frights:animations/tasks/easy/tnt_test/detonator/rig/variants/default/zzz/apply_to_node_stick_bone
$execute as $(sparks_bone) run function fossil_frights:animations/tasks/easy/tnt_test/detonator/rig/variants/default/zzz/apply_to_node_sparks_bone
$execute as $(main) run function fossil_frights:animations/tasks/easy/tnt_test/detonator/rig/variants/default/zzz/apply_to_node_main