# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(turntable_bone) {transformation: [0.866f,0f,-0.5f,0.5f,0f,1f,0f,0.9688f,0.5f,0f,0.866f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 0}
$data merge entity $(drink_bone4) {transformation: [0.866f,0f,-0.5f,0.4989f,0f,1f,0f,1.2441f,0.5f,0f,0.866f,-0.0007f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 0}
$data merge entity $(glass_bone4) {transformation: [0.866f,0f,-0.5f,0.5f,0f,1f,0f,1.1881f,0.5f,0f,0.866f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 0}
$data merge entity $(liquid_bone4) {transformation: [0f,0f,0f,0.5f,0f,1f,0f,1.625f,0f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 0}