# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute store result score @s aj.id run scoreboard players add aj.last_id aj.id 1
# Data Manager: Initalize per-entity storage
function fossil_frights:animations/dinocoin/vending_machine/runtime/gu/get_entity_uuid_string
data modify storage fossil_frights:vending_machine_aj_temp args.uuid set from storage fossil_frights:vending_machine_aj_gu out
execute store result storage fossil_frights:vending_machine_aj_temp args.id int 1 run scoreboard players get @s aj.id
function fossil_frights:animations/dinocoin/vending_machine/runtime/data_manager/create_entry with storage fossil_frights:vending_machine_aj_temp args
# Data Manager: Prepare for Read / Write
execute store result storage fossil_frights:vending_machine_aj_temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Read
function fossil_frights:animations/dinocoin/vending_machine/runtime/data_manager/read with storage fossil_frights:vending_machine_aj_temp args
data modify storage fossil_frights:vending_machine_aj_temp entry.data.uuids append from storage fossil_frights:vending_machine_aj_gu out
data modify storage fossil_frights:vending_machine_aj_temp entry.data.root_uuid set from storage fossil_frights:vending_machine_aj_gu out
data modify storage fossil_frights:vending_machine_aj_temp entry.data.blueprint_id set value "fossil_frights:animations/dinocoin/sarcophagus/rig"
data modify storage fossil_frights:vending_machine_aj_temp entry.data.rig_hash set value "947797fd8b7ccbc958371291238be249860c9f760d6565eb2e0b42e8aae69676"
tp @s ~ ~ ~ ~ ~
execute on passengers if entity @s[tag=animation.talking_skull.node.mouth_bone] run function fossil_frights:animations/dinocoin/sarcophagus/rig/zzz/summon/as_node/mouth_bone
data modify storage fossil_frights:vending_machine_aj_temp entry.data.uuids append from storage fossil_frights:vending_machine_aj_gu out
data modify storage fossil_frights:vending_machine_aj_temp entry.data.uuids_by_name.mouth_bone set from storage fossil_frights:vending_machine_aj_gu out
execute on passengers if entity @s[tag=animation.talking_skull.node.layer2] run function fossil_frights:animations/dinocoin/sarcophagus/rig/zzz/summon/as_node/layer2
data modify storage fossil_frights:vending_machine_aj_temp entry.data.uuids append from storage fossil_frights:vending_machine_aj_gu out
data modify storage fossil_frights:vending_machine_aj_temp entry.data.uuids_by_name.layer2 set from storage fossil_frights:vending_machine_aj_gu out
execute on passengers if entity @s[tag=animation.talking_skull.node.head_bone] run function fossil_frights:animations/dinocoin/sarcophagus/rig/zzz/summon/as_node/head_bone
data modify storage fossil_frights:vending_machine_aj_temp entry.data.uuids append from storage fossil_frights:vending_machine_aj_gu out
data modify storage fossil_frights:vending_machine_aj_temp entry.data.uuids_by_name.head_bone set from storage fossil_frights:vending_machine_aj_gu out
# Data Manager: Write
function fossil_frights:animations/dinocoin/vending_machine/runtime/data_manager/write with storage fossil_frights:vending_machine_aj_temp args
function fossil_frights:animations/dinocoin/sarcophagus/rig/zzz/set_default_pose
execute if data storage fossil_frights:vending_machine_aj_temp args.variant run function fossil_frights:animations/dinocoin/sarcophagus/rig/zzz/summon/zzz/variant_arg/no_variants_warning
execute if score #success aj.i matches 0 run return fail
execute if data storage fossil_frights:vending_machine_aj_temp args.animation run function fossil_frights:animations/dinocoin/sarcophagus/rig/zzz/summon/animation_arg/process with storage fossil_frights:vending_machine_aj_temp args
execute if score #success aj.i matches 0 run return fail
execute on passengers run rotate @s ~ ~
data modify entity @s teleport_duration set value 1
execute on passengers run data modify entity @s teleport_duration set value 1
tag @s remove aj.new
execute on passengers run tag @s remove aj.new