# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data remove storage fossil_frights:vending_machine_aj_temp args
$data modify storage fossil_frights:vending_machine_aj_temp args merge value {name:'$(name)', command:'$(command)', uuid:'+MISSING_UUID+'}
# Data Manager: Prepare for Read / Write
execute store result storage fossil_frights:vending_machine_aj_temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Read
function fossil_frights:animations/dinocoin/vending_machine/runtime/data_manager/read with storage fossil_frights:vending_machine_aj_temp args
function fossil_frights:animations/tasks/medium/feed_the_plants/flytrap/rig/zzz/as_node/as_data with storage fossil_frights:vending_machine_aj_temp args