# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage fossil_frights:animations/tasks/medium/feed_the_plants/flytrap/rig rig_hash set value 'a83918f006c7f640d609c973b328cfd09370653fda2f656396bf18ca88aac3ba'
scoreboard objectives add aj.eat.frame dummy