# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
scoreboard players set @s aj.idle_right.frame 0
tag @s add aj.transforms_only
execute at @s run function fossil_frights:animations/dinocoin/crane/rig/animations/idle_right/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only
tag @s remove animation.sculkadillo.animation.idle_right.playing