# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute store result score @s aj.id run scoreboard players add aj.last_id aj.id 1
# Data Manager: Initalize per-entity storage
function fossil_frights:animations/dinocoin/vending_machine/runtime/gu/get_entity_uuid_string
data modify storage fossil_frights:vending_machine_aj_temp args.uuid set from storage fossil_frights:vending_machine_aj_gu out
execute store result storage fossil_frights:vending_machine_aj_temp args.id int 1 run scoreboard players get @s aj.id
function fossil_frights:animations/dinocoin/vending_machine/runtime/data_manager/create_entry with storage fossil_frights:vending_machine_aj_temp args
# Data Manager: Prepare for Read / Write
execute store result storage fossil_frights:vending_machine_aj_temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Read
function fossil_frights:animations/dinocoin/vending_machine/runtime/data_manager/read with storage fossil_frights:vending_machine_aj_temp args
data modify storage fossil_frights:vending_machine_aj_temp entry.data.uuids append from storage fossil_frights:vending_machine_aj_gu out
data modify storage fossil_frights:vending_machine_aj_temp entry.data.root_uuid set from storage fossil_frights:vending_machine_aj_gu out
data modify storage fossil_frights:vending_machine_aj_temp entry.data.blueprint_id set value "fossil_frights:animations/tasks/easy/tnt_test/detonator/rig"
data modify storage fossil_frights:vending_machine_aj_temp entry.data.rig_hash set value "b8b7a3e491ce6a2992066e1945387c2a2c67d9f63a50cf45fd28d6d9838a8bda"
tp @s ~ ~ ~ ~ ~
execute on passengers if entity @s[tag=animation.detonator.node.stick_bone] run function fossil_frights:animations/tasks/easy/tnt_test/detonator/rig/zzz/summon/as_node/stick_bone
data modify storage fossil_frights:vending_machine_aj_temp entry.data.uuids append from storage fossil_frights:vending_machine_aj_gu out
data modify storage fossil_frights:vending_machine_aj_temp entry.data.uuids_by_name.stick_bone set from storage fossil_frights:vending_machine_aj_gu out
execute on passengers if entity @s[tag=animation.detonator.node.sparks_bone] run function fossil_frights:animations/tasks/easy/tnt_test/detonator/rig/zzz/summon/as_node/sparks_bone
data modify storage fossil_frights:vending_machine_aj_temp entry.data.uuids append from storage fossil_frights:vending_machine_aj_gu out
data modify storage fossil_frights:vending_machine_aj_temp entry.data.uuids_by_name.sparks_bone set from storage fossil_frights:vending_machine_aj_gu out
execute on passengers if entity @s[tag=animation.detonator.node.main] run function fossil_frights:animations/tasks/easy/tnt_test/detonator/rig/zzz/summon/as_node/main
data modify storage fossil_frights:vending_machine_aj_temp entry.data.uuids append from storage fossil_frights:vending_machine_aj_gu out
data modify storage fossil_frights:vending_machine_aj_temp entry.data.uuids_by_name.main set from storage fossil_frights:vending_machine_aj_gu out
# Data Manager: Write
function fossil_frights:animations/dinocoin/vending_machine/runtime/data_manager/write with storage fossil_frights:vending_machine_aj_temp args
function fossil_frights:animations/tasks/easy/tnt_test/detonator/rig/zzz/set_default_pose
execute if data storage fossil_frights:vending_machine_aj_temp args.variant run function fossil_frights:animations/tasks/easy/tnt_test/detonator/rig/zzz/summon/variant_arg/process with storage fossil_frights:vending_machine_aj_temp args
execute if score #success aj.i matches 0 run return fail
execute if data storage fossil_frights:vending_machine_aj_temp args.animation run function fossil_frights:animations/tasks/easy/tnt_test/detonator/rig/zzz/summon/animation_arg/process with storage fossil_frights:vending_machine_aj_temp args
execute if score #success aj.i matches 0 run return fail
execute on passengers run rotate @s ~ ~
data modify entity @s teleport_duration set value 1
execute on passengers run data modify entity @s teleport_duration set value 1
tag @s remove aj.new
execute on passengers run tag @s remove aj.new