# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
scoreboard players set #success aj.i 0
execute if data storage fossil_frights:vending_machine_aj_temp {args:{variant:''}} run return run function fossil_frights:animations/tasks/easy/tnt_test/detonator/rig/zzz/summon/variant_arg/if_empty
execute store success score #success aj.i run function fossil_frights:animations/tasks/easy/tnt_test/detonator/rig/zzz/summon/variant_arg/try_apply with storage fossil_frights:vending_machine_aj_temp args
execute unless score #success aj.i matches 1 run return run function fossil_frights:animations/tasks/easy/tnt_test/detonator/rig/zzz/summon/variant_arg/invalid_variant
scoreboard players set #success aj.i 1