# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$execute if function fossil_frights:animations/tasks/easy/tnt_test/detonator/rig/variants/$(variant)/apply run return 1
return fail