# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(strawtrapdoor_bone) {transformation: [-1f,0f,0f,0.5f,0f,1f,0f,2f,0f,0f,-1f,-0.0312f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 0}
$data merge entity $(trapdoor_ne_bone) {transformation: [-1f,0f,0f,0f,0f,1f,0f,0f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 0}
$data merge entity $(trapdoor_se_bone) {transformation: [-1f,0f,0f,0f,0f,1f,0f,0f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 0}
$data merge entity $(trapdoor_sw_bone) {transformation: [-1f,0f,0f,0f,0f,1f,0f,0f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 0}
$data merge entity $(trapdoor_nw_bone) {transformation: [-1f,0f,0f,0f,0f,1f,0f,0f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 0}
$data merge entity $(turntable_bone) {transformation: [1f,0f,0f,0.5f,0f,1f,0f,0.1563f,0f,0f,1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 0}
$data merge entity $(mainplate_bone) {transformation: [-1f,0f,0f,0f,0f,1f,0f,0f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 0}
$data merge entity $(straw_bone6) {transformation: [-1f,0f,0f,0.1875f,0f,0.999f,-0.0436f,1.0006f,0f,-0.0436f,-0.999f,0.1398f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 0}