# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$function fossil_frights:animations/tasks/medium/feed_the_plants/flytrap/rig/animations/eat/zzz/frames/$(frame) with storage fossil_frights:vending_machine_aj_temp entry.data.uuids_by_name
return 1