# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
tag @s remove animation.carnivorous_flytrap.animation.eat.playing
tag @s remove ff_feed_the_plants_flytrap_chewing
