# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function fossil_frights:tasks/medium/feed_the_plants/flytrap_eject_stick
kill @e[type=minecraft:item_display,tag=animation.carnivorous_flytrap.display_node.stick_bone,distance=..3,sort=nearest,limit=1]
tag @s remove animation.carnivorous_flytrap.animation.eat.playing
tag @s remove ff_feed_the_plants_flytrap_chewing
