# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(holder_l_bone) {transformation: [-1f,0f,0f,0.375f,0f,1f,0f,1f,0f,0f,-1f,0.1813f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 0}
$data merge entity $(holder_r_bone) {transformation: [-1f,0f,0f,0.375f,0f,1f,0f,1f,0f,0f,-1f,0.1938f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 0}
$data merge entity $(turntable_bone) {transformation: [1f,0f,0f,0.5f,0f,1f,0f,0.8062f,0f,0f,1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 0}
$data merge entity $(mainplate_bone) {transformation: [-1f,0f,0f,0f,0f,1f,0f,0.65f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 0}
$data merge entity $(straw_bone4) {transformation: [-1f,0f,0f,0.1875f,0f,1f,0f,1.4306f,0f,0f,-1f,0.1226f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 0}