# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
scoreboard players set @s aj.grab.frame 10
tag @s remove animation.sculkadillo.animation.grab.playing
