# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
# Data Manager: Prepare for Read / Write
execute store result storage fossil_frights:vending_machine_aj_temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Read
function fossil_frights:animations/dinocoin/vending_machine/runtime/data_manager/read with storage fossil_frights:vending_machine_aj_temp args
tag @s add animation.detonator.animation.activate.playing
scoreboard players set @s aj.activate.frame 0
tag @s add aj.transforms_only
execute at @s run function fossil_frights:animations/tasks/easy/tnt_test/detonator/rig/animations/activate/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only