# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
# Data Manager: Prepare for Read / Write
execute store result storage fossil_frights:vending_machine_aj_temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Read
function fossil_frights:animations/dinocoin/vending_machine/runtime/data_manager/read with storage fossil_frights:vending_machine_aj_temp args
execute unless data storage fossil_frights:vending_machine_aj_temp {entry:{data:{rig_hash: '9fe486558e0f41db07209a951b9c262b266e0d98617c52cbb62ff954882e4b92'}}} run function fossil_frights:animations/dinocoin/vending_machine/runtime/remove/outdated_rig
function fossil_frights:animations/dinocoin/vending_machine/rig/remove/this/zzz/0 with storage fossil_frights:vending_machine_aj_temp entry.data.uuids_by_name
function fossil_frights:animations/dinocoin/vending_machine/runtime/remove/entity_stack