# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify entity @s CustomName set value ['',{text:animation.sculkadillo,color:'#00aced'},'.',{text:bone,color:light_purple},'.',{text:right_ear_cube,color:gold}]
function fossil_frights:animations/dinocoin/vending_machine/runtime/gu/get_entity_uuid_string
scoreboard players operation @s aj.id = aj.last_id aj.id