# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
tag @s add aj.transforms_only
$execute store success score #success aj.i run function fossil_frights:animations/tasks/medium/feed_the_plants/flytrap/rig/animations/$(animation)/zzz/set_frame with storage fossil_frights:vending_machine_aj_temp args
tag @s remove aj.transforms_only
execute if score #success aj.i matches 1 run return 1
return fail