# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(lemontrapdoor_bone) {transformation: [-1f,0f,0f,0.4792f,0f,1f,0f,2f,0f,0f,-1f,-0.0625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 0}
$data merge entity $(turntable_bone) {transformation: [1f,0f,0f,0.5f,0f,1f,0f,0.9688f,0f,0f,1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 0}
$data merge entity $(drink_bone2) {transformation: [1f,0f,0f,0.4987f,0f,1f,0f,1.2441f,0f,0f,1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 0}
$data merge entity $(glass_bone2) {transformation: [1f,0f,0f,0.5f,0f,1f,0f,1.1881f,0f,0f,1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 0}