# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(spout_bone) {transformation: [-1.2083f,0f,0f,-0.0312f,0f,1.2083f,0f,0f,0f,0f,-1.2083f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 0}
$data merge entity $(spout_controller_bone) {transformation: [-1f,0f,0f,0.1875f,0f,1f,0f,0.9375f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 0}
$data merge entity $(turntable_bone) {transformation: [-1f,0f,0f,0.5f,0f,1f,0f,0.9688f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 0}
$data merge entity $(mainplate_bone) {transformation: [-1f,0f,0f,0f,0f,1f,0f,0.8125f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 0}
$data merge entity $(drink_bone2) {transformation: [0f,0f,0f,0.5013f,0f,0f,0f,0.7856f,0f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 0}
$data merge entity $(glass_bone2) {transformation: [-1f,0f,0f,0.5f,0f,1f,0f,0.9171f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 0}