# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$kill $(bottom_jaw_bone)
$kill $(top_jaw_bone)
$kill $(stem_bone)
$kill $(cotton_bone)
$kill $(stick_bone)
$kill $(main)