# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function fossil_frights:animations/dinocoin/vending_machine/runtime/gu/get_entity_uuid_string
data modify storage fossil_frights:vending_machine_aj_temp uuids append from storage fossil_frights:vending_machine_aj_gu out
execute on passengers run function fossil_frights:animations/dinocoin/vending_machine/runtime/util/zzz/0