# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute store result score @s aj.id run scoreboard players add aj.last_id aj.id 1
# Data Manager: Initalize per-entity storage
function fossil_frights:animations/dinocoin/vending_machine/runtime/gu/get_entity_uuid_string
data modify storage fossil_frights:vending_machine_aj_temp args.uuid set from storage fossil_frights:vending_machine_aj_gu out
execute store result storage fossil_frights:vending_machine_aj_temp args.id int 1 run scoreboard players get @s aj.id
function fossil_frights:animations/dinocoin/vending_machine/runtime/data_manager/create_entry with storage fossil_frights:vending_machine_aj_temp args
# Data Manager: Prepare for Read / Write
execute store result storage fossil_frights:vending_machine_aj_temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Read
function fossil_frights:animations/dinocoin/vending_machine/runtime/data_manager/read with storage fossil_frights:vending_machine_aj_temp args
data modify storage fossil_frights:vending_machine_aj_temp entry.data.uuids append from storage fossil_frights:vending_machine_aj_gu out
data modify storage fossil_frights:vending_machine_aj_temp entry.data.root_uuid set from storage fossil_frights:vending_machine_aj_gu out
data modify storage fossil_frights:vending_machine_aj_temp entry.data.blueprint_id set value "fossil_frights:animations/dinocoin/vending_machine/rig"
data modify storage fossil_frights:vending_machine_aj_temp entry.data.rig_hash set value "9fe486558e0f41db07209a951b9c262b266e0d98617c52cbb62ff954882e4b92"
tp @s ~ ~ ~ ~ ~
execute on passengers if entity @s[tag=animation.vending_machine.node.facade] run function fossil_frights:animations/dinocoin/vending_machine/rig/zzz/summon/as_node/facade
data modify storage fossil_frights:vending_machine_aj_temp entry.data.uuids append from storage fossil_frights:vending_machine_aj_gu out
data modify storage fossil_frights:vending_machine_aj_temp entry.data.uuids_by_name.facade set from storage fossil_frights:vending_machine_aj_gu out
execute on passengers if entity @s[tag=animation.vending_machine.node.lemontrapdoor_bone] run function fossil_frights:animations/dinocoin/vending_machine/rig/zzz/summon/as_node/lemontrapdoor_bone
data modify storage fossil_frights:vending_machine_aj_temp entry.data.uuids append from storage fossil_frights:vending_machine_aj_gu out
data modify storage fossil_frights:vending_machine_aj_temp entry.data.uuids_by_name.lemontrapdoor_bone set from storage fossil_frights:vending_machine_aj_gu out
execute on passengers if entity @s[tag=animation.vending_machine.node.strawtrapdoor_bone] run function fossil_frights:animations/dinocoin/vending_machine/rig/zzz/summon/as_node/strawtrapdoor_bone
data modify storage fossil_frights:vending_machine_aj_temp entry.data.uuids append from storage fossil_frights:vending_machine_aj_gu out
data modify storage fossil_frights:vending_machine_aj_temp entry.data.uuids_by_name.strawtrapdoor_bone set from storage fossil_frights:vending_machine_aj_gu out
execute on passengers if entity @s[tag=animation.vending_machine.node.trapdoor_ne_bone] run function fossil_frights:animations/dinocoin/vending_machine/rig/zzz/summon/as_node/trapdoor_ne_bone
data modify storage fossil_frights:vending_machine_aj_temp entry.data.uuids append from storage fossil_frights:vending_machine_aj_gu out
data modify storage fossil_frights:vending_machine_aj_temp entry.data.uuids_by_name.trapdoor_ne_bone set from storage fossil_frights:vending_machine_aj_gu out
execute on passengers if entity @s[tag=animation.vending_machine.node.trapdoor_se_bone] run function fossil_frights:animations/dinocoin/vending_machine/rig/zzz/summon/as_node/trapdoor_se_bone
data modify storage fossil_frights:vending_machine_aj_temp entry.data.uuids append from storage fossil_frights:vending_machine_aj_gu out
data modify storage fossil_frights:vending_machine_aj_temp entry.data.uuids_by_name.trapdoor_se_bone set from storage fossil_frights:vending_machine_aj_gu out
execute on passengers if entity @s[tag=animation.vending_machine.node.trapdoor_sw_bone] run function fossil_frights:animations/dinocoin/vending_machine/rig/zzz/summon/as_node/trapdoor_sw_bone
data modify storage fossil_frights:vending_machine_aj_temp entry.data.uuids append from storage fossil_frights:vending_machine_aj_gu out
data modify storage fossil_frights:vending_machine_aj_temp entry.data.uuids_by_name.trapdoor_sw_bone set from storage fossil_frights:vending_machine_aj_gu out
execute on passengers if entity @s[tag=animation.vending_machine.node.trapdoor_nw_bone] run function fossil_frights:animations/dinocoin/vending_machine/rig/zzz/summon/as_node/trapdoor_nw_bone
data modify storage fossil_frights:vending_machine_aj_temp entry.data.uuids append from storage fossil_frights:vending_machine_aj_gu out
data modify storage fossil_frights:vending_machine_aj_temp entry.data.uuids_by_name.trapdoor_nw_bone set from storage fossil_frights:vending_machine_aj_gu out
execute on passengers if entity @s[tag=animation.vending_machine.node.holder_l_bone] run function fossil_frights:animations/dinocoin/vending_machine/rig/zzz/summon/as_node/holder_l_bone
data modify storage fossil_frights:vending_machine_aj_temp entry.data.uuids append from storage fossil_frights:vending_machine_aj_gu out
data modify storage fossil_frights:vending_machine_aj_temp entry.data.uuids_by_name.holder_l_bone set from storage fossil_frights:vending_machine_aj_gu out
execute on passengers if entity @s[tag=animation.vending_machine.node.holder_r_bone] run function fossil_frights:animations/dinocoin/vending_machine/rig/zzz/summon/as_node/holder_r_bone
data modify storage fossil_frights:vending_machine_aj_temp entry.data.uuids append from storage fossil_frights:vending_machine_aj_gu out
data modify storage fossil_frights:vending_machine_aj_temp entry.data.uuids_by_name.holder_r_bone set from storage fossil_frights:vending_machine_aj_gu out
execute on passengers if entity @s[tag=animation.vending_machine.node.spout_bone] run function fossil_frights:animations/dinocoin/vending_machine/rig/zzz/summon/as_node/spout_bone
data modify storage fossil_frights:vending_machine_aj_temp entry.data.uuids append from storage fossil_frights:vending_machine_aj_gu out
data modify storage fossil_frights:vending_machine_aj_temp entry.data.uuids_by_name.spout_bone set from storage fossil_frights:vending_machine_aj_gu out
execute on passengers if entity @s[tag=animation.vending_machine.node.spout_controller_bone] run function fossil_frights:animations/dinocoin/vending_machine/rig/zzz/summon/as_node/spout_controller_bone
data modify storage fossil_frights:vending_machine_aj_temp entry.data.uuids append from storage fossil_frights:vending_machine_aj_gu out
data modify storage fossil_frights:vending_machine_aj_temp entry.data.uuids_by_name.spout_controller_bone set from storage fossil_frights:vending_machine_aj_gu out
execute on passengers if entity @s[tag=animation.vending_machine.node.turntable_bone] run function fossil_frights:animations/dinocoin/vending_machine/rig/zzz/summon/as_node/turntable_bone
data modify storage fossil_frights:vending_machine_aj_temp entry.data.uuids append from storage fossil_frights:vending_machine_aj_gu out
data modify storage fossil_frights:vending_machine_aj_temp entry.data.uuids_by_name.turntable_bone set from storage fossil_frights:vending_machine_aj_gu out
execute on passengers if entity @s[tag=animation.vending_machine.node.mainplate_bone] run function fossil_frights:animations/dinocoin/vending_machine/rig/zzz/summon/as_node/mainplate_bone
data modify storage fossil_frights:vending_machine_aj_temp entry.data.uuids append from storage fossil_frights:vending_machine_aj_gu out
data modify storage fossil_frights:vending_machine_aj_temp entry.data.uuids_by_name.mainplate_bone set from storage fossil_frights:vending_machine_aj_gu out
execute on passengers if entity @s[tag=animation.vending_machine.node.drink_bone] run function fossil_frights:animations/dinocoin/vending_machine/rig/zzz/summon/as_node/drink_bone
data modify storage fossil_frights:vending_machine_aj_temp entry.data.uuids append from storage fossil_frights:vending_machine_aj_gu out
data modify storage fossil_frights:vending_machine_aj_temp entry.data.uuids_by_name.drink_bone set from storage fossil_frights:vending_machine_aj_gu out
execute on passengers if entity @s[tag=animation.vending_machine.node.glass_bone] run function fossil_frights:animations/dinocoin/vending_machine/rig/zzz/summon/as_node/glass_bone
data modify storage fossil_frights:vending_machine_aj_temp entry.data.uuids append from storage fossil_frights:vending_machine_aj_gu out
data modify storage fossil_frights:vending_machine_aj_temp entry.data.uuids_by_name.glass_bone set from storage fossil_frights:vending_machine_aj_gu out
execute on passengers if entity @s[tag=animation.vending_machine.node.straw_bone] run function fossil_frights:animations/dinocoin/vending_machine/rig/zzz/summon/as_node/straw_bone
data modify storage fossil_frights:vending_machine_aj_temp entry.data.uuids append from storage fossil_frights:vending_machine_aj_gu out
data modify storage fossil_frights:vending_machine_aj_temp entry.data.uuids_by_name.straw_bone set from storage fossil_frights:vending_machine_aj_gu out
execute on passengers if entity @s[tag=animation.vending_machine.node.liquid_bone] run function fossil_frights:animations/dinocoin/vending_machine/rig/zzz/summon/as_node/liquid_bone
data modify storage fossil_frights:vending_machine_aj_temp entry.data.uuids append from storage fossil_frights:vending_machine_aj_gu out
data modify storage fossil_frights:vending_machine_aj_temp entry.data.uuids_by_name.liquid_bone set from storage fossil_frights:vending_machine_aj_gu out
execute on passengers if entity @s[tag=animation.vending_machine.node.drink_bone2] run function fossil_frights:animations/dinocoin/vending_machine/rig/zzz/summon/as_node/drink_bone2
data modify storage fossil_frights:vending_machine_aj_temp entry.data.uuids append from storage fossil_frights:vending_machine_aj_gu out
data modify storage fossil_frights:vending_machine_aj_temp entry.data.uuids_by_name.drink_bone2 set from storage fossil_frights:vending_machine_aj_gu out
execute on passengers if entity @s[tag=animation.vending_machine.node.glass_bone2] run function fossil_frights:animations/dinocoin/vending_machine/rig/zzz/summon/as_node/glass_bone2
data modify storage fossil_frights:vending_machine_aj_temp entry.data.uuids append from storage fossil_frights:vending_machine_aj_gu out
data modify storage fossil_frights:vending_machine_aj_temp entry.data.uuids_by_name.glass_bone2 set from storage fossil_frights:vending_machine_aj_gu out
execute on passengers if entity @s[tag=animation.vending_machine.node.straw_bone2] run function fossil_frights:animations/dinocoin/vending_machine/rig/zzz/summon/as_node/straw_bone2
data modify storage fossil_frights:vending_machine_aj_temp entry.data.uuids append from storage fossil_frights:vending_machine_aj_gu out
data modify storage fossil_frights:vending_machine_aj_temp entry.data.uuids_by_name.straw_bone2 set from storage fossil_frights:vending_machine_aj_gu out
execute on passengers if entity @s[tag=animation.vending_machine.node.liquid_bone2] run function fossil_frights:animations/dinocoin/vending_machine/rig/zzz/summon/as_node/liquid_bone2
data modify storage fossil_frights:vending_machine_aj_temp entry.data.uuids append from storage fossil_frights:vending_machine_aj_gu out
data modify storage fossil_frights:vending_machine_aj_temp entry.data.uuids_by_name.liquid_bone2 set from storage fossil_frights:vending_machine_aj_gu out
execute on passengers if entity @s[tag=animation.vending_machine.node.lemon_bone] run function fossil_frights:animations/dinocoin/vending_machine/rig/zzz/summon/as_node/lemon_bone
data modify storage fossil_frights:vending_machine_aj_temp entry.data.uuids append from storage fossil_frights:vending_machine_aj_gu out
data modify storage fossil_frights:vending_machine_aj_temp entry.data.uuids_by_name.lemon_bone set from storage fossil_frights:vending_machine_aj_gu out
execute on passengers if entity @s[tag=animation.vending_machine.node.drink_bone3] run function fossil_frights:animations/dinocoin/vending_machine/rig/zzz/summon/as_node/drink_bone3
data modify storage fossil_frights:vending_machine_aj_temp entry.data.uuids append from storage fossil_frights:vending_machine_aj_gu out
data modify storage fossil_frights:vending_machine_aj_temp entry.data.uuids_by_name.drink_bone3 set from storage fossil_frights:vending_machine_aj_gu out
execute on passengers if entity @s[tag=animation.vending_machine.node.glass_bone3] run function fossil_frights:animations/dinocoin/vending_machine/rig/zzz/summon/as_node/glass_bone3
data modify storage fossil_frights:vending_machine_aj_temp entry.data.uuids append from storage fossil_frights:vending_machine_aj_gu out
data modify storage fossil_frights:vending_machine_aj_temp entry.data.uuids_by_name.glass_bone3 set from storage fossil_frights:vending_machine_aj_gu out
execute on passengers if entity @s[tag=animation.vending_machine.node.straw_bone3] run function fossil_frights:animations/dinocoin/vending_machine/rig/zzz/summon/as_node/straw_bone3
data modify storage fossil_frights:vending_machine_aj_temp entry.data.uuids append from storage fossil_frights:vending_machine_aj_gu out
data modify storage fossil_frights:vending_machine_aj_temp entry.data.uuids_by_name.straw_bone3 set from storage fossil_frights:vending_machine_aj_gu out
execute on passengers if entity @s[tag=animation.vending_machine.node.liquid_bone3] run function fossil_frights:animations/dinocoin/vending_machine/rig/zzz/summon/as_node/liquid_bone3
data modify storage fossil_frights:vending_machine_aj_temp entry.data.uuids append from storage fossil_frights:vending_machine_aj_gu out
data modify storage fossil_frights:vending_machine_aj_temp entry.data.uuids_by_name.liquid_bone3 set from storage fossil_frights:vending_machine_aj_gu out
execute on passengers if entity @s[tag=animation.vending_machine.node.drink_bone4] run function fossil_frights:animations/dinocoin/vending_machine/rig/zzz/summon/as_node/drink_bone4
data modify storage fossil_frights:vending_machine_aj_temp entry.data.uuids append from storage fossil_frights:vending_machine_aj_gu out
data modify storage fossil_frights:vending_machine_aj_temp entry.data.uuids_by_name.drink_bone4 set from storage fossil_frights:vending_machine_aj_gu out
execute on passengers if entity @s[tag=animation.vending_machine.node.glass_bone4] run function fossil_frights:animations/dinocoin/vending_machine/rig/zzz/summon/as_node/glass_bone4
data modify storage fossil_frights:vending_machine_aj_temp entry.data.uuids append from storage fossil_frights:vending_machine_aj_gu out
data modify storage fossil_frights:vending_machine_aj_temp entry.data.uuids_by_name.glass_bone4 set from storage fossil_frights:vending_machine_aj_gu out
execute on passengers if entity @s[tag=animation.vending_machine.node.straw_bone4] run function fossil_frights:animations/dinocoin/vending_machine/rig/zzz/summon/as_node/straw_bone4
data modify storage fossil_frights:vending_machine_aj_temp entry.data.uuids append from storage fossil_frights:vending_machine_aj_gu out
data modify storage fossil_frights:vending_machine_aj_temp entry.data.uuids_by_name.straw_bone4 set from storage fossil_frights:vending_machine_aj_gu out
execute on passengers if entity @s[tag=animation.vending_machine.node.liquid_bone4] run function fossil_frights:animations/dinocoin/vending_machine/rig/zzz/summon/as_node/liquid_bone4
data modify storage fossil_frights:vending_machine_aj_temp entry.data.uuids append from storage fossil_frights:vending_machine_aj_gu out
data modify storage fossil_frights:vending_machine_aj_temp entry.data.uuids_by_name.liquid_bone4 set from storage fossil_frights:vending_machine_aj_gu out
execute on passengers if entity @s[tag=animation.vending_machine.node.drink_bone5] run function fossil_frights:animations/dinocoin/vending_machine/rig/zzz/summon/as_node/drink_bone5
data modify storage fossil_frights:vending_machine_aj_temp entry.data.uuids append from storage fossil_frights:vending_machine_aj_gu out
data modify storage fossil_frights:vending_machine_aj_temp entry.data.uuids_by_name.drink_bone5 set from storage fossil_frights:vending_machine_aj_gu out
execute on passengers if entity @s[tag=animation.vending_machine.node.glass_bone5] run function fossil_frights:animations/dinocoin/vending_machine/rig/zzz/summon/as_node/glass_bone5
data modify storage fossil_frights:vending_machine_aj_temp entry.data.uuids append from storage fossil_frights:vending_machine_aj_gu out
data modify storage fossil_frights:vending_machine_aj_temp entry.data.uuids_by_name.glass_bone5 set from storage fossil_frights:vending_machine_aj_gu out
execute on passengers if entity @s[tag=animation.vending_machine.node.straw_bone5] run function fossil_frights:animations/dinocoin/vending_machine/rig/zzz/summon/as_node/straw_bone5
data modify storage fossil_frights:vending_machine_aj_temp entry.data.uuids append from storage fossil_frights:vending_machine_aj_gu out
data modify storage fossil_frights:vending_machine_aj_temp entry.data.uuids_by_name.straw_bone5 set from storage fossil_frights:vending_machine_aj_gu out
execute on passengers if entity @s[tag=animation.vending_machine.node.liquid_bone5] run function fossil_frights:animations/dinocoin/vending_machine/rig/zzz/summon/as_node/liquid_bone5
data modify storage fossil_frights:vending_machine_aj_temp entry.data.uuids append from storage fossil_frights:vending_machine_aj_gu out
data modify storage fossil_frights:vending_machine_aj_temp entry.data.uuids_by_name.liquid_bone5 set from storage fossil_frights:vending_machine_aj_gu out
execute on passengers if entity @s[tag=animation.vending_machine.node.drink_bone6] run function fossil_frights:animations/dinocoin/vending_machine/rig/zzz/summon/as_node/drink_bone6
data modify storage fossil_frights:vending_machine_aj_temp entry.data.uuids append from storage fossil_frights:vending_machine_aj_gu out
data modify storage fossil_frights:vending_machine_aj_temp entry.data.uuids_by_name.drink_bone6 set from storage fossil_frights:vending_machine_aj_gu out
execute on passengers if entity @s[tag=animation.vending_machine.node.glass_bone6] run function fossil_frights:animations/dinocoin/vending_machine/rig/zzz/summon/as_node/glass_bone6
data modify storage fossil_frights:vending_machine_aj_temp entry.data.uuids append from storage fossil_frights:vending_machine_aj_gu out
data modify storage fossil_frights:vending_machine_aj_temp entry.data.uuids_by_name.glass_bone6 set from storage fossil_frights:vending_machine_aj_gu out
execute on passengers if entity @s[tag=animation.vending_machine.node.straw_bone6] run function fossil_frights:animations/dinocoin/vending_machine/rig/zzz/summon/as_node/straw_bone6
data modify storage fossil_frights:vending_machine_aj_temp entry.data.uuids append from storage fossil_frights:vending_machine_aj_gu out
data modify storage fossil_frights:vending_machine_aj_temp entry.data.uuids_by_name.straw_bone6 set from storage fossil_frights:vending_machine_aj_gu out
execute on passengers if entity @s[tag=animation.vending_machine.node.liquid_bone6] run function fossil_frights:animations/dinocoin/vending_machine/rig/zzz/summon/as_node/liquid_bone6
data modify storage fossil_frights:vending_machine_aj_temp entry.data.uuids append from storage fossil_frights:vending_machine_aj_gu out
data modify storage fossil_frights:vending_machine_aj_temp entry.data.uuids_by_name.liquid_bone6 set from storage fossil_frights:vending_machine_aj_gu out
# Data Manager: Write
function fossil_frights:animations/dinocoin/vending_machine/runtime/data_manager/write with storage fossil_frights:vending_machine_aj_temp args
function fossil_frights:animations/dinocoin/vending_machine/rig/zzz/set_default_pose
execute if data storage fossil_frights:vending_machine_aj_temp args.variant run function fossil_frights:animations/dinocoin/vending_machine/rig/zzz/summon/zzz/variant_arg/no_variants_warning
execute if score #success aj.i matches 0 run return fail
execute if data storage fossil_frights:vending_machine_aj_temp args.animation run function fossil_frights:animations/dinocoin/vending_machine/rig/zzz/summon/animation_arg/process with storage fossil_frights:vending_machine_aj_temp args
execute if score #success aj.i matches 0 run return fail
execute on passengers run rotate @s ~ ~
data modify entity @s teleport_duration set value 1
execute on passengers run data modify entity @s teleport_duration set value 1
tag @s remove aj.new
execute on passengers run tag @s remove aj.new