# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(shell_bone) {transformation: [-0.9856f,0f,-0.1693f,-0.4458f,0f,1f,0f,0.3462f,0.1693f,0f,-0.9856f,-0.4345f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_ear_cube) {transformation: [-0.9856f,0f,-0.1693f,-0.306f,0f,1f,0f,0.6875f,0.1693f,0f,-0.9856f,-0.1745f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_ear_cube) {transformation: [-0.9856f,0f,-0.1693f,-0.4908f,0f,1f,0f,0.6875f,0.1693f,0f,-0.9856f,-0.1428f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head_bone) {transformation: [-0.9856f,0f,-0.1693f,-0.4153f,0f,1f,0f,0.6563f,0.1693f,0f,-0.9856f,-0.2572f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(tail) {transformation: [-0.9856f,0f,-0.1693f,-0.5106f,0f,1f,0f,0.375f,0.1693f,0f,-0.9856f,-0.8116f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(arm_koin_bone) {transformation: [0f,0f,0f,-0.3292f,0f,0f,0f,0.4143f,0f,0f,0f,-0.1885f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(front_left_leg_bone) {transformation: [-0.9757f,-0.1412f,-0.1675f,-0.367f,-0.0358f,0.8571f,-0.514f,0.5f,0.2162f,-0.4955f,-0.8413f,-0.3448f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(front_right_leg_bone) {transformation: [-0.7281f,-0.4756f,-0.4937f,-0.5444f,-0.3144f,0.8717f,-0.376f,0.4594f,0.6092f,-0.1185f,-0.7841f,-0.3162f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(back_left_leg_bone) {transformation: [-1f,0f,0f,-0.375f,0f,1f,0f,0.1875f,0f,0f,-1f,-0.75f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(back_right_leg_bone) {transformation: [-1f,0f,0f,-0.625f,0f,1f,0f,0.1875f,0f,0f,-1f,-0.75f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(handle_bone) {transformation: [-0.6018f,0.7986f,0f,-0.5f,0.7986f,0.6018f,0f,0.0625f,0f,0f,-1f,-0.0625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(lever) {transformation: [-1f,0f,0f,-0.5f,0f,1f,0f,0.0625f,0f,0f,-1f,-0.0625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}