# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(mouth_bone) { transformation: [0.9239f,0f,-0.3827f,0f,0f,1f,0f,0.0938f,0.3827f,0f,0.9239f,0f,0f,0f,0f,1f], start_interpolation: 0 }
$data merge entity $(layer2) { transformation: [0.9239f,0f,-0.3827f,0f,0f,1f,0f,0f,0.3827f,0f,0.9239f,0f,0f,0f,0f,1f], start_interpolation: 0 }
$data merge entity $(head_bone) { transformation: [0.9239f,0f,-0.3827f,0f,0f,1f,0f,0f,0.3827f,0f,0.9239f,0f,0f,0f,0f,1f], start_interpolation: 0 }