# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
tag @s remove animation.vending_machine.animation.fill_bubblybat.playing
tag @s remove animation.vending_machine.animation.fill_pteranadontwist.playing
tag @s remove animation.vending_machine.animation.fill_fossilfizz.playing
tag @s remove animation.vending_machine.animation.fill_choruscola.playing
tag @s remove animation.vending_machine.animation.fill_raptorrush.playing
tag @s remove animation.vending_machine.animation.fill_velocitea.playing