# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(lemontrapdoor_bone) {transformation: [-1f,0f,0f,0.4583f,0f,1f,0f,2f,0f,0f,-1f,-0.0625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 0}
$data merge entity $(strawtrapdoor_bone) {transformation: [-1f,0f,0f,0.5f,0f,1f,0f,2f,0f,0f,-1f,-0.0312f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 0}
$data merge entity $(holder_l_bone) {transformation: [-1f,0f,0f,0.3128f,0f,1f,0f,1f,0f,0f,-1f,0.1875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 0}
$data merge entity $(holder_r_bone) {transformation: [-1f,0f,0f,0.3128f,0f,1f,0f,1f,0f,0f,-1f,0.1875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 0}
$data merge entity $(spout_bone) {transformation: [-1.2083f,0f,0f,-0.0417f,0f,1.2083f,0f,0f,0f,0f,-1.2083f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 0}
$data merge entity $(spout_controller_bone) {transformation: [-1f,0f,0f,0.1771f,0f,1f,0f,0.9375f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 0}