# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage fossil_frights:animations/dinocoin/vending_machine/rig rig_hash set value '9fe486558e0f41db07209a951b9c262b266e0d98617c52cbb62ff954882e4b92'
scoreboard objectives add aj.fill_bubblybat.frame dummy
scoreboard objectives add aj.fill_pteranadontwist.frame dummy
scoreboard objectives add aj.fill_fossilfizz.frame dummy
scoreboard objectives add aj.fill_jurassicjuice.frame dummy
scoreboard objectives add aj.fill_raptorrush.frame dummy
scoreboard objectives add aj.fill_velocitea.frame dummy