# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
scoreboard objectives remove aj.fill_bubblybat.frame
scoreboard objectives remove aj.fill_pteranadontwist.frame
scoreboard objectives remove aj.fill_fossilfizz.frame
scoreboard objectives remove aj.fill_jurassicjuice.frame
scoreboard objectives remove aj.fill_raptorrush.frame
scoreboard objectives remove aj.fill_velocitea.frame
tellraw @a [[{color:gray,text:'\n '},{color:'#00aced',text:'ᴀɴɪᴍᴀᴛᴇᴅ ᴊᴀᴠᴀ'},{color:dark_gray,italic:true,text:'\n (fossil_frights:animations/dinocoin/vending_machine/rig)'},'\n → '],[{text:'Successfully uninstalled ',color:green},{text:'fossil_frights:animations/dinocoin/vending_machine/rig',color:yellow},{text:'!'},{text:'\n If you have exported multiple times, you may have to remove objectives from previous exports manually, as Animated Java only knows about the objectives from the most recent export.',color:gray,italic:true}],'\n']