# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
# Data Manager: Prepare for Read / Write
execute store result storage fossil_frights:vending_machine_aj_temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Read
function fossil_frights:animations/dinocoin/vending_machine/runtime/data_manager/read with storage fossil_frights:vending_machine_aj_temp args
function fossil_frights:animations/dinocoin/vending_machine/rig/zzz/set_default_pose