# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless score @s aj.id matches -2147483648..2147483647 run return run tellraw @a [{text:'',color:red},[{color:gray,text:'\n '},{color:'#00aced',text:'ᴀɴɪᴍᴀᴛᴇᴅ ᴊᴀᴠᴀ'},{color:dark_gray,italic:true,text:'\n (fossil_frights:animations/dinocoin/sarcophagus/rig)'},'\n → '],'ᴇʀʀᴏʀ: ',{text:'Function Not Executed as Entity with ID Score',underlined:true},'\n\n ',{text:'[This Function]',color:yellow,hover_event:{action:show_text,value:[{color:yellow,text:'fossil_frights:animations/dinocoin/sarcophagus/rig/as_root'}]}},' must be executed as an entity with a ',{text:aj.id,color:yellow},' score.','\n']
# Data Manager: Prepare for Read / Write
execute store result storage fossil_frights:vending_machine_aj_temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Read
function fossil_frights:animations/dinocoin/vending_machine/runtime/data_manager/read with storage fossil_frights:vending_machine_aj_temp args
$data modify storage fossil_frights:vending_machine_aj_temp args.command set value '$(command)'
data modify storage fossil_frights:vending_machine_aj_temp args.root_uuid set from storage fossil_frights:vending_machine_aj_temp entry.data.root_uuid
function fossil_frights:animations/dinocoin/sarcophagus/rig/as_root_entity with storage fossil_frights:vending_machine_aj_temp args