# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage fossil_frights:animations/dinocoin/sarcophagus/rig rig_hash set value '947797fd8b7ccbc958371291238be249860c9f760d6565eb2e0b42e8aae69676'
scoreboard objectives add aj.jump.frame dummy
scoreboard objectives add aj.idle.frame dummy