# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
scoreboard objectives add aj.i dummy
scoreboard objectives add aj.id dummy
scoreboard objectives add aj.is_rig_loaded dummy
scoreboard objectives add aj.tween_duration dummy
scoreboard players add aj.last_id aj.id 0
function fossil_frights:animations/dinocoin/vending_machine/runtime/gu/on_load
function fossil_frights:animations/dinocoin/vending_machine/runtime/data_manager/on_load
