# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bottom_jaw_bone) {transformation: [-1f,0f,0f,0.0233f,0f,1f,0f,1.6576f,0f,0f,-1f,0.4688f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(top_jaw_bone) {transformation: [-0.9848f,-0.1736f,0f,-0.0142f,-0.1736f,0.9848f,0f,1.6264f,0f,0f,-1f,0.4688f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(stem_bone) {transformation: [-1f,0f,0f,0f,0f,1f,0f,-0.1094f,0f,0f,-1f,0.0313f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(cotton_bone) {transformation: [0f,-0.9986f,0.0523f,0.664f,-1f,0f,0f,1.6354f,0f,-0.0523f,-0.9986f,0.0541f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(stick_bone) {transformation: [0f,-0.9986f,0.0523f,1.413f,-1f,0f,0f,1.6354f,0f,-0.0523f,-0.9986f,0.0933f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(main) {transformation: [-1.225f,0f,0f,0f,0f,1.225f,0f,-0.1094f,0f,0f,-1.225f,0.0313f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}