# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
scoreboard players set #success aj.i 0
execute if data storage fossil_frights:vending_machine_aj_temp {args:{animation:''}} run return run function fossil_frights:animations/dinocoin/vending_machine/rig/zzz/summon/animation_arg/if_empty
execute store result storage fossil_frights:vending_machine_aj_temp args.frame int 1 store result score #frame aj.i run data get storage fossil_frights:vending_machine_aj_temp args.frame
execute if score #frame aj.i matches ..-1 run return run function fossil_frights:animations/dinocoin/vending_machine/rig/zzz/summon/animation_arg/no_negative
execute store success score #success aj.i run function fossil_frights:animations/dinocoin/vending_machine/rig/zzz/summon/animation_arg/try_set_frame with storage fossil_frights:vending_machine_aj_temp args
execute unless score #success aj.i matches 1 run return run function fossil_frights:animations/dinocoin/vending_machine/rig/zzz/summon/animation_arg/invalid_animation
execute if data storage fossil_frights:vending_machine_aj_temp {args:{start_animation: true}} run function fossil_frights:animations/dinocoin/vending_machine/rig/zzz/summon/animation_arg/start_animation with storage fossil_frights:vending_machine_aj_temp args
scoreboard players set #success aj.i 1