# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
scoreboard players set @s aj.activate.frame 0
tag @s add aj.transforms_only
execute at @s run function fossil_frights:animations/tasks/easy/tnt_test/detonator/rig/animations/activate/zzz/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only
tag @s remove animation.detonator.animation.activate.playing