# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
scoreboard players set @s aj.pull_back.frame 24
tag @s remove animation.sculkadillo.animation.pull_back.playing
