# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(stick_bone) {transformation: [-1f,0f,0f,0.5f,0f,1f,0f,0f,0f,0f,-1f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(sparks_bone) {transformation: [-1f,0f,0f,-0.125f,0f,1f,0f,0.7969f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(main) {transformation: [-1f,0f,0f,0.5f,0f,1f,0f,0f,0f,0f,-1f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}